apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapp
  name: simpleapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - image: omarkorety/simpleapp:V${BUILD_NUMBER}
        name: simpleapp
#         imagePullPolicy: Always
        ports:
        - containerPort: 50001
        resources: {}
