apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleapp-service
  name: simpleapp-service
spec:
  ports:
  - name: simpleapp-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: simpleapp
  type: LoadBalancer
status:
  loadBalancer: {}
